export const AUDIENCE_ADD = 'AUDIENCE_ADD'
export const AUDIENCE_EDIT_NAME = 'AUDIENCE_EDIT_NAME'
export const AUDIENCE_EDIT_DESCRIPTION = 'AUDIENCE_EDIT_DESCRIPTION'
export const AUDIENCE_EDIT_STRATEGY = 'AUDIENCE_EDIT_STRATEGY'